### ISSUE TITLE
Return download path 

### ISSUE THREAD

**Issue by chahank** [osm-flex/osm-flex#12]
The methods to download data dumps should return the download path. This would simplify query writing when using the default locations.

**Comment by peanutfun** [comment]
@chahank Can you give some more context? The public functions in https://github.com/osm-flex/osm-flex/blob/main/src/osm_flex/download.py all download files to a `save_path` you can specify in the function parameters. What it it you want to do? Should the functions only return the URLs instead of downloading the data?

**Comment by chahank** [comment]
It should just return the output path. This is very handy when the default location is used.

**Comment by Evelyn-M** [comment]
solved with pull request #27
